coze:
  base_url: "https://api.coze.cn"
  app_id: "1182425168827"
  public_key: "pCdS-X6Rg5wlrjEZ6lQ30RcUYhg6zJDJjjS74YF_mZE"
  private_key_path: "./pem/private_key.pem"
  http_timeout: 300
  workflow_ids:
    WORKFLOW_SUMMARY: "7467074695335067675"
    WORKFLOW_SCRIPT: "7467097121859452937"